spring.application.name=order-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/orderservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Server Configuration
server.port=8082

# Keycloak / JWT Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/surplus
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/surplus/protocol/openid-connect/certs

# Keycloak Configuration
keycloak.adminClientId=order-client
keycloak.adminClientSecret=zt3n1vTrWTw8qPeTxZpziOge6YRUHyoh
keycloak.urls.auth=http://localhost:8180
keycloak.realm=surplus
jwt.auth.converter.resource-id=order-client

# Validation Configuration
spring.jpa.open-in-view=false