spring.application.name=user-management
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/users
spring.data.mongodb.database=users
server.port=8080

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Keycloak Configuration
keycloak.adminClientId=surplus-client
keycloak.adminClientSecret=VnCbRm4iJzc7HU1opi2RkSnxKakG0GkD
keycloak.urls.auth=http://localhost:8180
keycloak.realm=surplus
jwt.auth.converter.resource-id=surplus-client


# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/surplus
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/surplus/protocol/openid-connect/certs

logging.level.org.springframework.security=DEBUG
